name: Update EPG File

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download EPG file
        run: curl -L -o guiatv_color.xml.gz https://github.com/davidmuma/EPG_dobleM/raw/master/guiatv_color.xml.gz

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add guiatv_color.xml.gz
          git commit -m "Update EPG file"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
