name: Clone and compress DVB-Apps

on:
  push:
    branches:
      - main  # ajusta esto según el nombre de tu rama principal
  pull_request:
    branches:
      - main  # ajusta esto según el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Mercurial
      run: sudo apt-get update && sudo apt-get install -y mercurial

    - name: Clone dvb-apps repository
      run: hg clone http://linuxtv.org/hg/dvb-apps

    - name: Compress files
      run: tar --exclude=".hg" -cjf dvb-apps.tar.bz2 dvb-apps

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dvb-apps.tar.bz2  # Nombre del archivo de artefacto
        path: dvb-apps.tar.bz2  # Ruta del archivo comprimido
